services:
  edc-provider:
    networks:
      - soofi-network
  
  portal-provider:
    networks:
      - soofi-network

  edc-consumer:
    networks:
      - soofi-network

  portal-consumer:
    networks:
      - soofi-network

  edc-consumer-mcp:
    networks:
      - soofi-network