services:
  edc-provider:
    networks:
      - soofi-network
  
  portal-provider:
    networks:
      - soofi-network

  edc-consumer:
    networks:
      - soofi-network

  portal-consumer:
    networks:
      - soofi-network

  edc-consumer-mcp:
    ports: !override
      - "8087:8081"
    networks:
      - soofi-network

  flowise:
    networks:
      - soofi-network

  flowise-init:
    networks:
      - soofi-network

  aas-env:
    networks:
      - soofi-network

  aas-registry:
    networks:
      - soofi-network

  sm-registry:
    networks:
      - soofi-network

  aas-web-ui:
      ports: !override
      - "3001:3000"   
      networks:
      - soofi-network

