name: soofi-trainer

include:
  - path: compose/knowledge.yml
    project_directory: .
  - path: compose/training.yml
    project_directory: .
  - path: compose/interaction.yml
    project_directory: .
  - path: compose/tools.yml
    project_directory: .

# ===========================================
# Networks
# ===========================================
networks:
  soofi-network:
    driver: bridge
    name: soofi-network
  soofi-training-network:
    driver: bridge
    name: soofi-training-network
