services:
  aas-discovery:
    image: eclipsebasyx/aas-discovery:${BASYX_VERSION}
    container_name: aas-discovery
    environment:
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    volumes:
      - ./compose/aas/config/aas-discovery.yml:/application/application.yml
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '100m'
    networks:
      - soofi-aas-network

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:${BASYX_VERSION}
    container_name: aas-registry
    environment:
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      #KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092  
    volumes:
      - ./compose/aas/config/aas-registry.yml:/workspace/config/application.yml
    restart: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - soofi-aas-network

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:${BASYX_VERSION}
    container_name: sm-registry
    environment:
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      #KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    volumes:
      - ./compose/aas/config/sm-registry.yml:/workspace/config/application.yml
    restart: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - soofi-aas-network

  aas-environment:
    image: eclipsebasyx/aas-environment:${BASYX_VERSION}
    container_name: aas-environment
    environment:
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry:8080
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://sm-registry:8080
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION: http://aas-discovery:8081
      BASYX_EXTERNALURL: https://${AAS_HOSTNAME}:${AAS_ENVIRONMENT_PORT}
      BASYX_ENVIRONMENT: file:/application/files/aasx/
      SERVER_FORWARD_HEADERS_STRATEGY: framework
    volumes:
      - ./compose/aas/aasx:/application/files/aasx
      - ./compose/aas/config/aas-env.yml:/application/application.yml
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - soofi-aas-network

  aas-webui:
    image: eclipsebasyx/aas-gui:${AAS_WEBUI_V3_VERSION}
    container_name: aas-webui
    environment:
      CHOKIDAR_USEPOLLING: "true"
      AAS_REGISTRY_PATH: https://${AAS_HOSTNAME}:${AAS_REGISTRY_PORT}/shell-descriptors
      SUBMODEL_REGISTRY_PATH: https://${AAS_HOSTNAME}:${SM_REGISTRY_PORT}/submodel-descriptors
      AAS_REPO_PATH: https://${AAS_HOSTNAME}:${AAS_ENVIRONMENT_PORT}/shells
      SUBMODEL_REPO_PATH: https://${AAS_HOSTNAME}:${AAS_ENVIRONMENT_PORT}/submodels
      CD_REPO_PATH: https://${AAS_HOSTNAME}:${AAS_ENVIRONMENT_PORT}/concept-descriptions
      AAS_DISCOVERY_PATH: https://${AAS_HOSTNAME}:${AAS_DISCOVERY_PORT}/lookup/shells
      PRIMARY_COLOR: '#7C3131'
      LOGO_PATH: dfki_Logo_digital_black.png
    restart: always
    depends_on:
      aas-environment:
        condition: service_healthy
    volumes:
      - ./compose/aas/data:/usr/src/app/dist/Logo
    networks:
      - soofi-aas-network

include:
  #- path: aas_mnestix.yml
  #  project_directory: .

